apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
  labels:
    app: vpromc
spec:
  selector:
    matchLabels:
      app: vpromc
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
      - name: vpromc
        image: memcached:1.6
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: vpromc
spec:
  ports:
  - port: 11211
    targetPort: 11211
    protocol: TCP
  selector:
    app: vpromc
