apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpronginx
  labels:
    app: vpronginx
spec:
  selector:
    matchLabels:
      app: vpronginx
  replicas: 1
  template:
    metadata:
      labels:
        app: vpronginx
    spec:
      containers:
      - name: vpronginx
        image: vprofile-nginx:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vpronginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: vpronginx
